### ISSUE TITLE
he ftp server is no longer responding. Indeed ps -augx shows that it is not even running and there is a core dump in /.

### ISSUE THREAD

**Issue by mohammadsajal** [mohammadsajal/-Uploading-file-causes-FTP-server-to-dump-core#2]

**Comment by Shreyaaax** [comment]
Not our code, Jill, that’s just proftpd which comes with Linux.

**Comment by mohammadsajal** [comment]
That doesn’t sound right. I’ve never been able to crash proftpd when I connect with a normal ftp client. Our code crashes it every single time. Ftp servers don’t just “crash”.

**Comment by Shreyaaax** [comment]
Mikey(Kim), can you look at this? Maybe your client code is doing something wrong.

**Comment by BowonKim** [comment]
I think I was passing the user name instead of the password or something…

**Comment by mohammadsajal** [comment]
Still happens in Build 2021.

**Comment by BowonKim** [comment]
Whoa. That’s strange. Lemme debug this.

**Comment by BowonKim** [comment]
I’m thinking it might be MikeyStrCpy()…

**Comment by BowonKim** [comment]
Ahhh!
FIXED!

**Comment by mohammadsajal** [comment]
Appears fixed in build 2022, so I’ll go ahead and close this.
